### PR TITLE
Add localization

### PR DESCRIPTION
**Pull request by monodo**
This PR:

- Adds i18next as localization library
- Adds and edits translation files. Please feel free to fix translation error, for German in particular
- Adds data-i18next attributes where applicable. ´´´select´´´ options do not get translated so far. The option definition mode is responsible for this. For instance, for ´´´optClipMode´´´ select, translating ´´´No clipping´´´ would cause an error.

@m-schuetz please review & merge

### CODE REVIEW

**Comment by m-schuetz** [comment]
Hey Olivier, 

Sorry this is taking so long, I'm having trouble reviewing all the changes because there are too much files/changes and github won't display the actual changes.
Could you remove the il8next library from the PR and just point me to a download link to the right i8next version?

**Comment by monodo** [comment]
Well, I used this i18next, v1.8.2, you can get it from [there](https://github.com/jsdelivr/jsdelivr/tree/master/files/i18next). I'll upgrade tu v2 later...

**Comment by monodo** [comment]
i18n files are now deleted

**Comment by m-schuetz** [comment]
Merged it now. Thanks again for the PR.

Stuff that is left to do in develop branch (will do that myself)
Add spaces after the colon:
image

**Comment by monodo** [comment]
Thanks a lot ! I'll soon work on some UI enhancements...

**Pull request merged**
