### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Maartenvm**
Greyhound support for Potree.

Demo gallery with some sample data to demonstrate the interaction at [http://potree.entwine.io](http://potree.entwine.io).

### CODE REVIEW

**Comment by m-schuetz** [comment]
Okay, trying to give this a shot now. Looks like there will be lots of merge conflicts as well as unnecessary merges so I'll have to experiment a bit on how to merge only the relevant files without losing your commits.

**Comment by m-schuetz** [comment]
Btw, for next time, please don't use a formatter. It makes things difficult if virtually every file is marked as changed.

**Comment by dkastl** [comment]
@m-schuetz I found `.editorconfig` a simple and convenient way to not have to worry about different ways of formatting. Most editors these days handle the conventions described in the configuration file: http://editorconfig.org/

**Comment by m-schuetz** [comment]
@Maartenvm @connormanning 
Okay, got the biggest chunk merged into https://github.com/potree/potree/tree/Maartenvm-develop, able to see the autzen stadium now. Cool stuff! Some errors left, will have to do some more stuff to catch up with some of the latest refactoring to potree.

@dkastl Interesting, will be taking a look at that.

**Comment by m-schuetz** [comment]
Merged into develop. I've added a few Bugs in the process which I'm going to tackle before it reaches the master. 

Thanks for this Pull Request! It's nice to have support for other indexing systems.

**Pull request merged**
