### PR TITLE
Allows editing of the annotation title and description

### PR DESCRIPTION
**Pull request by rob-waring**
Allows programmatic editing of the title and description of annotations, without affecting the external API of the Annotation class.

### CODE REVIEW

**Comment by m-schuetz** [comment]
Did you test if this works if the tile variable is a jquery element? In examples/annotations.html, some annotation titles are actually jquery elements, e.g.:

```javascript

let elTitle = $(`
	<span>
		About Annotations
		<img src="${Potree.resourcePath}/icons/goto.svg" 
			name="action_set_scene"
			class="annotation-action-icon" 
			style="filter: invert(1);" />
	</span>
`);
elTitle.find("img[name=action_set_scene]").click( (event) => {
	event.stopPropagation();
	viewer.setScene(sceneLion); 
});
elTitle.toString = () => "About Annotations";
let aAbout1 = new Potree.Annotation({
	position: [590043.63, 231490.79, 740.78],
	title: elTitle,
	cameraPosition: [590105.53, 231541.63, 782.05],
	cameraTarget: [590043.63, 231488.79, 740.78],
	description: `<ul><li>Click on the annotation label to move a predefined view.</li> 
	<li>Click on the icon to execute the specified action.</li>
	In this case, the action will bring you to another scene and point cloud.</ul>`
});
sceneSG.annotations.add(aAbout1);

```

**Comment by rob-waring** [comment]
Cheers for the code, I'll give that a check now :)

**Comment by rob-waring** [comment]
You're right, it didn't. It does now, by emptying and replacing the content. That was the only way I could see of being able to use text, html or jQuery objects as the new title/description.

**Comment by m-schuetz** [comment]
And thanks for this one too!

**Pull request merged**
