### PR TITLE
Profile DXF download

### LINKED ISSUE #569: Profile extraction in 2D
Hello,
The profile tool is great because it displays a straightened view of the points along the axis. This type of view is essential for professional applications (eg rockfall trajectories). It would be really nice to be able to export this view in a scaled and straightened vector format. Currently the CSV export lists the points with their 3D coordinates and therefore does not meet this need. It would take a CSV export on both X and Z axes, following the path of the profile.
Is that possible ? What function should be changed to achieve this?
At a minimum, would it be possible to allow 3D DXF extraction of profiles in the same way as distance measurements?
Thank you very much and congratulations for your work.

### LINKED ISSUE #1193: Profile of multiple pointclouds downloads as split pointclouds
From example _"multiple pointclouds"_:

`.LAS` file:

And `.CSV` coordinates are not matching either.

### PR DESCRIPTION
**Pull request by roy-mdr**
# Profile DXF download

## 2D DXF (flat, unfolded: as plotted in the profile viewer)

This feature adds a button to the profile viewer "DXF(2D)" which allows you to download the view from the (flat, unfolded) profile viewer to a .DXF

Fixes #569 

## 3D DXF (real coordinates)

Fixes #1193 

This feature adds a button to the profile viewer "DXF(3D)" which allows you to download the 3D profile to a .DXF, similar as the already existing .LAS format.

> Possible warnings commented [here](https://github.com/potree/potree/pull/1178#issuecomment-1152382550) and [here](https://github.com/potree/potree/pull/1178#issuecomment-1152411849)

## Preview
In browser:
ss

In Rhino 7:
rhino

### CODE REVIEW

**Comment by tmvtool** [comment]
Hi, Thanks for this tool that seems to be perfect but i have a problem to implement this tool. I have modified all the lines recommended in these files (but don't see the new button dxf 2D) : profile.html, dxfprofileexporter.js, profile.js and add the svg file but nothing changes in my potree.
Do i need to rebuild npm ? What is the procedure to rebuild ?

Thanks

**Comment by roy-mdr** [comment]
> Hi, Thanks for this tool that seems to be perfect but i have a problem to implement this tool. I have modified all the lines recommended in these files (but don't see the new button dxf 2D) : profile.html, dxfprofileexporter.js, profile.js and add the svg file but nothing changes in my potree.
> Do i need to rebuild npm ? What is the procedure to rebuild ?
> 
> Thanks

Hi! Yes, you have to modify the source files before the build. I didn't test to rebuild on top of another one but that should work too.

**Comment by tmvtool** [comment]
Thanks but i already modify the source files and nothing happened in my profile tool. How can i build please step by step ? Thanks  a lot

**Comment by tmvtool** [comment]
Hi,

I get the picture to download the dxf file but this is my problem now when i go to the console : 

Uncaught ReferenceError: DXFProfileExporter is not defined
    at HTMLImageElement.<anonymous> (profile.js:509:6)
    at HTMLImageElement.dispatch (jquery-3.1.1.min.js:3:10315)
    at HTMLImageElement.q.handle (jquery-3.1.1.min.js:3:8342)
(anonymes) @ profile.js:509
dispatch @ jquery-3.1.1.min.js:3
q.handle @ jquery-3.1.1.min.js:3

Any ideas ?  Thanks a lot

**Comment by roy-mdr** [comment]
> Hi,
> 
> I get the picture to download the dxf file but this is my problem now when i go to the console :
> 
> Uncaught ReferenceError: DXFProfileExporter is not defined at HTMLImageElement. (profile.js:509:6) at HTMLImageElement.dispatch (jquery-3.1.1.min.js:3:10315) at HTMLImageElement.q.handle (jquery-3.1.1.min.js:3:8342) (anonymes) @ profile.js:509 dispatch @ jquery-3.1.1.min.js:3 q.handle @ jquery-3.1.1.min.js:3
> 
> Any ideas ? Thanks a lot

Hi! Yes that's because you are not downloading my changes (this branch changes)

1. download [my potree branch](https://github.com/soloelroy/potree/tree/profile-dxf) or manually change the files you need (displayed in this pull request)
1. cd to folder
1. run `npm install`
1. `npm start` to test
	1. go to http://localhost:1234/examples/

**Comment by tmvtool** [comment]
Hi, Ok now it works ! But i needed to modify the potree.js directly for the code javascript : my potree app read the potree.js that's the reason why i couldn't see the changes done when i insert your code into profile.js or DXFProfileExporter.js

I have another question, is it possible to load all the points of the profile into an dxf file ? For example if my profile is 20 meters wide, can i save all the points into my dxf file ?

Thanks again for the good job !

**Comment by roy-mdr** [comment]
> I have another question, is it possible to load all the points of the profile into an dxf file ? For example if my profile is 20 meters wide, can i save all the points into my dxf file ?

My code just dumps all the points rendered in the profile view to a DXF files, the number of points displayed in the view is another issue treated [here](https://github.com/potree/potree/issues/241#issuecomment-278008068).
As you describe your question, if your model is 20mts wide and is rendering all the 20mts in the profile view, it will export all your points without problem!

**Comment by tmvtool** [comment]
I tested to reduce the width of my profile but i had the same results : it will export only the points along my profile line (i got only 2000 points). In your test do you succeed to export all the points (on your first post we saw a profile with 5m wide but in Rhino it seems to be a line) ? Thanks for your help

**Comment by roy-mdr** [comment]
## Test with profile width of 5:



## Test with profile width of 50:



---

My tip is that you should let run for a while the rendering of the profile viewer until the number of points stop counting up, then you download the DXF.
I don't know how the code decides when to stop rendering points but you can look for that in the code! Maybe it depends on machine specs or in the size of the model, idk.

**Comment by tmvtool** [comment]
Thanks for the tip, i understand now what do you mean, the points are well exported but all the points are in the same line (and depends of the downloading in potree).
My wish is to get all the points in the real coordinates (like the export in csv or las), in order to work on the real position of the points in Autocad with the dxf file.

**Comment by roy-mdr** [comment]
Oh! I see now. In that case you can open the LAS file in your photogrammetry software and export the DXF from it :)

**Comment by mriedo** [comment]
Thanks @soloelroy for this cool new function for the profile. It's a very interesting addition
 will be very useful for us. I installed it on our potree viewer and it works. I have the same wish as @tmvtool to get all the points in the real coordinates (like the export in csv or las), in order to work on the real position of the points in a CAD systems or drawing systems : Rhino, Microstation, Archicad, Autocad, Sketchup, Solidworks, Cadwork, Mapublisher and many other software (for instance : Illustrator) used by our users 
- unfortunately, not all CAD have a LAS import function as standard function ... often an expensive plugin or not available at all
- it's more coherent to have the 3 export functions CSV, LAS and DXF with the same real world coordinates

**Comment by roy-mdr** [comment]
Due to the interest and demand for this feature it is now fully implemented :)
Hope you enjoy!

**Comment by mriedo** [comment]
Thanks so much @soloelroy for this very quick implementation ! That's really awesome and it will be very useful !

I installed this on our dev [LiDAR geoportal](https://sitn.ne.ch/lidar/dev/) with nice > 100 billions points datasets. 
profile1

The 2D DXF profile looks fine 

2d_profile_rhino

but seems the 3D DXF profile is not right ... it is split in 3 parts and not in real world coordinates 
3d_profile_rhino

Maybe it is split in 3 because I made the profile with 3 pointclouds activated ?

Here [a video](https://sitn.ne.ch/web/diffusion/videos/potree/dxf3dpotree.mp4) showing the process using only 1 pointcloud (mobile lidar) ... real world coordinates are x>2 million, y > 1 million 

Tell me if you need more information or more tests. I would be happy to help !

Thanks again and best regards

**Comment by roy-mdr** [comment]
> but seems the 3D DXF profile is not right ... it is split in 3 parts and not in real world coordinates
> 
> Maybe it is split in 3 because I made the profile with 3 pointclouds activated ?
> 
> Here [a video](https://sitn.ne.ch/web/diffusion/videos/potree/dxf3dpotree.mp4) showing the process using only 1 pointcloud (mobile lidar) ... real world coordinates are x>2 million, y > 1 million


Hi! Thanks for the info! And that's an unbelievable pointcloud you have!
Yes, it seems to be that the 3 parts are corresponding to the layers and definitely messing with the real world coordinates... However this seems to be a core bug because the `.LAS` file is downloaded the same way (split in 3 parts) and I assume the `.CSV` file is also bad written.
What seems weird is that if you hover in the profile viewer, the coordinates are correct.

Let me have a look and see if I can hunt this bug!

**Comment by mriedo** [comment]
Yes, we have some nice pointclouds
- 4 aerial LiDAR surveys 2001 pt/sqm, 2010 10pts/sqm, 2016 30 pts/sqm, 2018 15 pts/sqm ... and a new 2022 soon coming with 100pts/sqm 
- 1 mobile lidar of 500 km roads with > 5000 pts/sqm
- 1 bathymetric sonar & lidar survey for the lake

A little contribution to the [http://www.theeartharchive.com/](url) vision 

You are right, it seems to be a core bug. The 3D LAS export is also wrong, not in real coordinates and split. I wasn't aware of this problem.

Thanks a lot if you can take a look !

**Comment by roy-mdr** [comment]
Hi, I already found the issue but I'm concerned about the quantization of big coordinates (as seen [here](https://github.com/potree/potree/issues/621)).

Can you please give it a try with your pointclouds?

You need to modify `potree\src\viewer\profile.js` and replace the function **_getProfilePoints_** in the line **_488_** for this modified version:
```js
let getProfilePoints = (truePosition) => {
	let points = new Points();
	
	for(let [pointcloud, entry] of this.pointclouds){
		for(let pointSet of entry.points){

			let originPos = pointSet.data.position;
			let truePointPosition = new Float32Array(originPos);
			for(let i = 0; i < pointSet.numPoints; i++){
				if (truePosition === true) {
					truePointPosition[3 * i + 0] += pointcloud.position.x;
					truePointPosition[3 * i + 1] += pointcloud.position.y;
				}
				truePointPosition[3 * i + 2] += pointcloud.position.z;
			}

			pointSet.data.position = truePointPosition;
			points.add(pointSet);
			pointSet.data.position = originPos;
			console.log("REAL COORDS - POINTSET:", pointSet)
		}
	console.log("REAL COORDS - POINTCLOUD:", pointcloud)
	}

	return points;
};
```

Also in the same file replace the snippet `$('#potree_download_dxf3D_icon').click()` (now line **_525_**) with this one:

```js
$('#potree_download_dxf3D_icon').click(() => {
	
	const points = getProfilePoints(true);

	const string = DXFProfileExporter.toString(points);

	const blob = new Blob([string], {type: "text/string"});
	$('#potree_download_profile_dxf3D_link').attr('href', URL.createObjectURL(blob));
});
```

Now try to download the 3D DXF and hope it wont quantize your points :S

**Comment by roy-mdr** [comment]
## TEST

Multiple pointclouds:


Before:


After:


## Note

From the geopackage exmaple (with big coordinates in Y) it seems that is not being quantized (or at least noticeable). However the point density varies as the width of the profile changes:


This is, again, an issue treated [here](https://github.com/potree/potree/issues/241#issuecomment-278008068). Maybe I could look for a workaround but the cons are the same; mainly _performance issues_.

---

Please let me know how this fix is working for you and I'll commit :)

**Comment by mriedo** [comment]
> You need to modify `potree\src\viewer\profile.js` and replace the function **_getProfilePoints_** in the line **_488_** for this modified version:

I did this and published to [https://sitn.ne.ch/lidar/dev/](url)

It solved the problem with multiple pointclouds and the real world coordinates are right 👍 
I am impressed ... you are very good !!! 
lidar_dxf3d_profile
The only problem remaining is the quantization of big coordinates you mention 
quantization
Thanks so much !

**Comment by roy-mdr** [comment]
Just committed 😃
Please try this update because it may improve the precision about the quantization problem.

**Comment by mriedo** [comment]
Thanks so much @roy-mdr ! I published and tested this version and it works fine : quantization problem solved  @!
quantization_solved
quantization_solved2

**Comment by tmvtool** [comment]
@roy-mdr it is really a great job and improve a lot the management of our pointclouds. thanks a lot ! Thanks @mriedo for the following of the discussion too !
I just have an ultimate suggestion about the export from the profile exporter. Is there a way to export more than 100 000 points ? We have the perfect tool but just limited by the number of points we could extract. Thanks a lot for your amazing work

**Comment by mriedo** [comment]
- I didn't know this limitation
- With LAS3D export, you don't have the 100'000 points limitations from what I just tested. I was able to export a LAS profil with 250'000 points
- I am not sure DXF is the perfect format for storing big amount of points ... it's not compact at all, it's not a pointcloud format 
- Usually for a profile, 100'000 points is already quite good

**Comment by tmvtool** [comment]
- I have a limitation directly in the window of the profile exporter
- Did you test the las extract tool ? Because in Rhino when i select one point (with CTRL+MAJ + area of selection) i discovered sometimes i had many points superposed, this bug appears when i extract a very large area (300*300 meters for example)
- For a profile 100 000 points is enough but i want to extract points inside an area

**Comment by roy-mdr** [comment]
Hi @tmvtool ! I didn't realize your name... Stands for what I think of? 🎶🪬🎶

I don't know if this is a bug or a DXF limitation...
I will check this issue as soon as I can, however I have a few trivial points and hope you can help me:

- What about the performance issues when using (really) dense pointclouds assuming we bypass the intended limitation for rendering the profile in the profile viewer (and ignoring DXF only goes to 100,000)
- should be a separate UI (button / slider) when someone wants a denser section? How should it be?
- Do you think this profile tool is the right tool for extracting large areas? (Not technically, but conceptually)

Any other thoughts are welcome!

---

Also any examples, screenshots or your potree website would be a lot of help! Thanks!

**Comment by tmvtool** [comment]
That's exactly what do you think ! The Mars Volta and tool band 🎶🎶
This is our [lidar portal](http://lidarconsult.geocannes.fr/potree/pagename.html)

- Bypassing the limitation will not be a problem, 700/800k points are easily handled with a good PC
- Some suggestions : a slider could be perfect, or to have the option to export all the points (it is really easy to decimate the pointcloud with many other tools) / a progress bar when exporting ?
- Conceptually for extracting points, the best way could be to export all the points inside an area from the construction of a polygon
Thanks a lot master of potree !

**Comment by roy-mdr** [comment]
So... Oh boy...

I found the bypass.

## Here is a gift for you:
omg

## *But...*
When I tried to download the DXF:
omg2

## However
This is still progress!
I managed to download a thinner profile with 707,608 points
omg3

And it's pretty!
omg5

## *But...* (Again)
After doing an overkill on the pointcloud it reduced to 226,094 points :(

---

# Please conclude!

So this is my conclusion so far:

**Even though I think this is doable, I don't think this is the right approach to a tool for this needs...**

Now imagine the code is fixed and working with all the point on its place... I have a 10th gen i9 with GTX1060 and using Rhino and AutoCAD was nearly impossible with so many points, and even Potree crashed when trying to export that many points... (again, even tho I think is doable, I don't think is the right approach). Should I mention I was rendering while testing? 🤪 (I don't think that would change my mind)

I just think that this may be work for a native software like CloudCompare or Metashape with native pointcloud files, and not for CAD with DXFs...

---

If you want to try my code you can download my [full-profile](https://github.com/roy-mdr/potree/tree/full-profile) branch and install it :) the bypass is activated so be careful!

---

But we should be happy because The Mars Volta returned after 9 years! 😁😁

**Comment by roy-mdr** [comment]
I forgot to clarify some points made before:

**With the actual code:**
- I was able to download DXFs with more than 200,000 points. So is not a limitation of DXF nor a bug on the code... Is just the way the profiles are programmed to render.
- I overkilled some pointclouds and indeed found duplicated points... But again I think this could be the way Potree renders the profile (future bug-fix), the model itself or even the threshold of the overkill removing not-really-overlapped points (I need to do further testing) but honestly this issue does not bothers me so much rn...

**Comment by tmvtool** [comment]
I realized my message wasn't sent to you...
So i implement your devolpment but ihad this error on my website

profile.js:187 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'data')
    at ProfileFakeOctree.createNewBatch (profile.js:187:39)
    at ProfileFakeOctree.addPoints (profile.js:127:15)
    at ProfileWindow.addPoints (profile.js:800:7)
    at ProfileWindowController.progressHandler (profile.js:1113:3)
    at Object.onProgress (GeoJSONExporter.js:45:11)
    at ProfileRequest.updateGenerator (ProfileRequest.js:163:12)
    at updateGenerator.next (<anonymous>)
    at ProfileRequest.update (ProfileRequest.js:105:4)
    at Object.updatePointClouds (Potree_update_visibility.js:13:19)
    at Viewer.update (viewer.js:1871:1)

It seems to be a loop, because the errors increase one after one.
Is there someting i miss in the code ?

For Mars Volta i hope news songs will be better than the new one...

**Comment by m-schuetz** [comment]
Cool stuff, thanks for this PR!

**Pull request merged**
