### PR TITLE
Added AngleTool

### PR DESCRIPTION
**Pull request by Maartenvm**
On request of the archeologists we're working with, we made a tool to display angles between lines based on the pre-existing AreaTool. 

I've added it to the lion examples as well.

PS: Heads up: something (that I didn't change) seems to have been changed in line 1551 of the built potree.js.

### CODE REVIEW

**Comment by potree** [comment]
Sounds sweet!
I'll be gone for the next week and look at it when I'm back.

**Comment by m-schuetz** [comment]
Hello Maarten!

Nice tool. Unfortunately I can't merge it automatically anymore so I will somehow stuff it into the develop branch. 
Do you also have the svg file for angle.png?

**Comment by Maartenvm** [comment]
?Nope sry made it with pixel art ;)


________________________________

**Comment by m-schuetz** [comment]
Included it now, at least in viewer.html. Other examples will be updated before next release"

**Comment by m-schuetz** [comment]
https://github.com/potree/potree/commit/ca2ec014e96dadb78357c23d4b8c57bfc1f85b4f

**Pull request closed without merging**
