### PR TITLE
Dispose invisible objects

### PR DESCRIPTION
**Pull request by michel-kraemer**
Hi Markus!

As discussed earlier I send you our proposal for memory management. The new function `disposeInvisible` disposes all objects that are not visible anymore. This is a very aggressive method as it does not care whether there is still enough free memory or not, but it makes sure memory does not overflow even for very large point clouds.

We tested the new function with a point cloud that is 14GB large and it works quite well. I hope you can merge the code or at least use it as a starting point to implement a more clever way to dispose objects. For example, you could collect objects to be disposed in a queue and only delete them after n frames or after m other nodes have been loaded or something like that.

Cheers,
Michel

### CODE REVIEW

**Comment by m-schuetz** [comment]
Hello Michel,

Thanks for the PR! It is a good starting point for me.
Rather than disposing all invisible nodes, I'd like to dispose least recently used nodes after a certain memory threshold has been reached. That way, nodes that might still be used often are kept in memory for future use.

**Comment by michel-kraemer** [comment]
Yes, that would be great! Of course the threshold should be configurable. At least in our case we really need this aggressive type of garbage collection and we would set a really low threshold I guess.

Cheers,
Michel

**Comment by m-schuetz** [comment]
I've implemented disposing least recently used nodes in the memory_management branch.
In the viewer, the load limit is set to two times the visible points limit: 
https://github.com/potree/potree/blob/develop/examples/viewer.html#L504

If you need immediate disposal of invisible nodes, you can set the pointLoadLimit to visible point limit.

```Potree.pointLoadLimit = pointCountTarget * 1 * 1000 * 1000;```

**Comment by michel-kraemer** [comment]
Perfect. Thanks a lot!

**Pull request closed without merging**
